### ISSUE TITLE
Add patching functions

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan-tools#1]
## User story

I want patches to be easy to apply as part of the make process
_??I want to easily generate patches when I have modified the Drupal or DKAN  codebase??_

## Acceptance Criteria

* I can apply arbitray patches to the docroot

**Comment by dafeder** [comment]
For applying patches, this may just be a question of using the override make files correctly...

**Comment by kimwdavidson** [comment]
Doing this work as a custom command for client that needs it.
