### ISSUE TITLE
Add an option to make dkan2 without the frontend

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan-tools#114]
It is great that dkan-tools brings a front-end for us when "making" the codebase, but the ultimate intention is that each catalog will have control over the frontend. This means that we do not need that step from make at some point in the process. It would be great to have an option to not get the frontend and maybe look in src for an available frontend that gets connected to docroot.

**Comment by erogray** [comment]
@fmizzell can you add a bit more info about what's involved here?

**Comment by erogray** [comment]
@fmizzell can you add a bit more info about what's involved here?

**Comment by janette** [comment]
@fmizzell what if the default was 'without' the frontend and use a  flag on the make command if you want it to include the frontend in the build

**Comment by erogray** [comment]
@fmizzell can you provide more info about the details here?

**Comment by fmizzell** [comment]
https://github.com/GetDKAN/dkan-tools/pull/130
