### ISSUE TITLE
circular soft link in src/modules

### ISSUE THREAD

**Issue by ketwaroo** [GetDKAN/dkan-tools#129]
Every time `dktl make` is run it creates a circular link in to a `modules` folder. If there are custom modules on the project we end up with errors like:

> The website encountered an unexpected error. Please try again later.
RuntimeException: SplFileInfo::openFile(/var/www/docroot/modules/custom/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/modules/custom_module/custom_module.info.yml): failed to open stream: No such file or directory in SplFileInfo->openFile() (line 458 of /var/www/docroot/core/lib/Drupal/Core/Extension/ExtensionDiscovery.php).

**Comment by erogray** [comment]
@fmizzell can you review?

**Comment by kimwdavidson** [comment]
DKAN2
