### ISSUE TITLE
Use DKTL for DKAN PRs on Circle

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan-tools#14]
This may not require any changes to dktl tool, but rather creating a bash script in dkan's .circle folder that makes the paralelization work. Perhaps a helper PHP function is needed to recreate some of the logic currently in the ruby scripts.

## Acceptance criteria

* DKTL test commands are used to run tests on circle
* Circle paralelization logic is either in a bash script under .circle/ or in the PHP app... or take another stab at using circle 2 API?

## Work
Work has been happening both in dkan-tools and in the dkan repo:
https://github.com/GetDKAN/dkan/tree/dktl-circle
https://github.com/GetDKAN/dkan-tools/tree/exit

### Work Left

1. In dkan-tools, we have some exit calls in our dktl bash script that are too early and are bypassing relevant code. We want to capture the exit code from the relevant commands and exit later with the appropriate code.
1. In dkan, I started to work with circleci's cli-tool to parallelize our test runs, but the work is not finished, we want to be able to run both phpunit and behat tests in parallel.

**Comment by woodt** [comment]
Reworked circleci config to use workflows to run the behat and unit tests in parallel; made some minor tweaks to dkan-tools so that dktl works OK in the circleci execution environment.
