### ISSUE TITLE
.gitignore files not deleted when src/themes doesn't exist

### ISSUE THREAD

**Issue by dharizza** [GetDKAN/dkan-tools#152]
If folder src/themes does not exist in the codebase, running `dktl make` doesn't finishes correctly, the message `[error]  Could not link themes. Folders 'src/themes' and 'docroot' must both be present to create link.` is shown and then lots of .gitignore files are not deleted.

**Comment by fmizzell** [comment]
I believe https://github.com/GetDKAN/dkan-tools/pull/156 addresses this issue.

**Comment by janette** [comment]
true!
