### ISSUE TITLE
Intermittent error: unable to add drush and DKAN2 dependencies

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan-tools#201]
Per @thejuliekramer in https://github.com/GetDKAN/dkan-tools/issues/146:

```dktl make```  worked but had this warning:

```
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package getdkan/dkan2 is abandoned, you should avoid using it. Use getdkan/dkan instead.

Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package getdkan/dkan2 is abandoned, you should avoid using it. Use getdkan/dkan instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.

 [WARNING] Skipping linking /var/www/src/schema. Folders /var/www/src/schema and 'docroot' must both be present to
           create link.
```

`dktl install --demo` worked but had this warning: 

```
sh: 1: frontend:install: not found
 [Exec]  Exit code 127  Time 0.006s
 [Exec] Running frontend:build in /var/www/docroot
sh: 1: frontend:build: not found
 [Exec]  Exit code 127  Time 0.003s
```

**Comment by janette** [comment]
https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates#s-troubleshooting-permission-issues-prevent-running-composer

**Comment by dafeder** [comment]
Issue is the permissions on the src/site dir being set too restrictively after `dktl install`. On a new install, they're completely open after `dktl make` but get set to 555 after install. Did some research, this is a known issue with the drupal scaffold plugin and how it works in composer.

https://www.drupal.org/project/drupal/issues/3091285

There are two workarounds I see while they figure this out:

1. Add a `chmod u+w /var/www/src/sites/default` to the end of `dktl install`
2. Disable scaffolding for that file as described in comments [52 and 53](https://www.drupal.org/project/drupal/issues/3091285#comment-13452779)

#1 seems like the better option to me.
