### ISSUE TITLE
Support create-react-app frontend with frontend:install

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan-tools#227]
Details:

- Add an option to dktl frontend:install to specify git URL, but have it default to data-catalog-react (create react-app) frontend
- Rename symlinked dir to just "frontend"
- Update gatsby to work with "frontend" dir name

**Comment by janette** [comment]
to do: update dkan-tools README instructions for updating the prod .env file

**Comment by janette** [comment]
fixed by #253
