### ISSUE TITLE
Init should not override existing composer.json

### ISSUE THREAD

**Issue by rhabbachi** [GetDKAN/dkan-tools#259]
**User Story**
Developers working on an existing DKAN2 project and running `dktl init` will see the custom `composer.json` replaced by the vanilla dkan-tools' `assets/composer.json`. This is problematic since we want to keep and control the changes introduced to this file.

**Acceptance Criteria**
- [ ] When `composer.json` file already exists, `dktl init` should error out.

**Comment by dafeder** [comment]
What is the use case for re-running `dktl init` but not overwriting the composer.json file?

**Comment by rhabbachi** [comment]
Say you have additional dependencies in your project other than the one provided by dktl. For example, for RI we will need to depend on migration modules.

Replacing the composer.json will cause the loss of those dependencies.
