### ISSUE TITLE
PHP Fatal error:  require_once(): Failed opening required '/usr/local/dkan-tools/bin/../vendor/autoload.php'

### ISSUE THREAD

**Issue by gchehab** [GetDKAN/dkan-tools#303]
**Describe the bug**
I am trying to deploy a dkan instance using dkan-tools but having this error during `dktl init`:

```
Creating myproject_db_1  ... done
Creating myproject_web_1 ... done
Creating myproject_cli_1 ... done
Connected dktl-proxy to "myproject_default" network.
PHP Warning:  require_once(/usr/local/dkan-tools/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/dkan-tools/bin/app.php on line 7
PHP Fatal error:  require_once(): Failed opening required '/usr/local/dkan-tools/bin/../vendor/autoload.php' (include_path='.:/usr/local/php/lib/php') in /usr/local/dkan-tools/bin/app.php on line 7
Restarting myproject_web_1 ... done
```
Am I missing something?

**Steps To Reproduce**
Cloned the repository both using master and tag 4.2.2.  Added dktl folder on path and run `dktl init` on a empty folder where the project is going to be.

Tried to install on ubuntu 20.04.3 LTS with Docker 20.10.8 and Docker-compose 1.29.1 (quite recent versions)

**Expected behavior**
Project should be initialized. 3 containers are up, but without a running application:

```
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS          PORTS                                                              NAMES
b3d657c659dc   getdkan/dkan-cli:v0.3.0    "/opt/startup.sh /us…"   10 minutes ago   Up 10 minutes   0.0.0.0:49251->8888/tcp                                            myproject_cli_1
25576e3c54f2   wodby/mariadb:10.3-3.8.5   "/docker-entrypoint.…"   10 minutes ago   Up 10 minutes   0.0.0.0:49247->3306/tcp                                            myproject_db_1
695aa0f149ee   traefik:v2.0               "/entrypoint.sh --lo…"   11 minutes ago   Up 11 minutes   0.0.0.0:80->80/tcp, 0.0.0.0:433->433/tcp, 0.0.0.0:8080->8080/tcp   dktl-proxy
```

**Comment by janette** [comment]
@gchehab did you run the rest of the steps?
```
dktl init
dktl make
dktl install
```

**Comment by gchehab** [comment]
Hi @janette,  I really can't remember, I was following the install instructions. However, I will try again and report the results.
Thanks

**Comment by tridoxx** [comment]
@gchehab hi you resolve the problem?

**Comment by gchehab** [comment]
Hey, guys, tried again today and worked without issues. Just used, as documented:
```
dktl init
dktl demo
```
Really could not figure out what went wrong in the previous attempts.

**Comment by tridoxx** [comment]
hi @gchehab how are you i can contact with you?, you are in the slack group? .I thank you
