### ISSUE TITLE
Add custom FQDN example

### ISSUE THREAD

**Issue by Azylog** [GetDKAN/dkan-tools#322]
Hello,
I've been asked by a customer to deploy a DKAN instance. I've never used neither dkan nor dkan-tools before.

When trying to setup the whole thing, I've been stopped by the lack of documentation to set the correct fqdn in traefik with dkan-tools.
After reading some sources, I found I've to set the DKTL_PROXY_DOMAIN environment variable before running the install process.

Perhaps could it be added to the documentation somewhere ? (like in chapter "Starting a new project, step-by-step")

Thanks !

**Comment by janette** [comment]
@Azylog our documentation, only covers local setup through the docker containers we use in our own project builds. If you are having issues you may want to explore a [new ddev option](https://getdkan.github.io/dkan-ddev-addon/) that is in the works, it is still experimental but if you are familiar with ddev you may have more luck.

**Comment by dafeder** [comment]
Closing this, as support for dkan-tools is coming to an end soon.
