### ISSUE TITLE
How to use demo site/data

### ISSUE THREAD

**Issue by kkounouni** [GetDKAN/dkan-tools#323]
Hello, we are using dkan 1 with drupal 7 for the government open data portal. 

Now, we are testing our options with dkan2. I have configured a new server Ubuntu 20.4 and installed dkan_tools.

After many testings ... Ηow can Ι use demo data after the execution of the following commands?

mkdir my_project && cd my_project
dktl init
dktl demo

Thanks in advance

**Comment by janette** [comment]
@kkounouni if you run `dktl url` and open the url it gives you, do you have a functioning site with 10 sample datasets?

**Comment by VitorFCM** [comment]
Hi there, I'm trying the same demo tutorial on my Fedora 35 without docker, but after run `dktl url` I got this result: **[error]  URI not available!**
I have installed mysql and changed my *src/site/settings.php* to
```php
<?php

foreach (scandir(__DIR__) as $file) {
        if (preg_match("/settings\..*\.php/", $file) == true
                && substr_count($file, "default") == 0) {
                include __DIR__ . "/{$file}";
        }
}

$config_directories['sync'] = '../config/sync';
$settings["config_sync_directory"] = '../config/sync';
$settings['hash_salt'] = 'iWkrYuVi0hNEFpXWd4baeJorqXaCJmrdu7eSje_JQQGRy3QtcDqrpl-hRLx5tRgECzTUjA0BXw';
$databases['default']['default'] = [
        'database' => 'drupal',
        'username' => 'drupal',
        'password' => 'passwordForDrupalUser',
        'host' => 'localhost',
        'port' => '3306',
        'driver' => 'mysql',
        'prefix' => '',
        'collation' => 'utf8mb4_general_ci',
        'init_commands' => [
                'big_selects' => 'SET SQL_BIG_SELECTS=1',
        ],
        'pdo' => [
                PDO::ATTR_TIMEOUT => 5,
        ],
];
```
If I `dktl demo` without this change the database access is denied.
What else should I do to start the demo and get the url?
Thanks!

**Comment by janette** [comment]
@VitorFCM 
Rather than running `dktl demo`, could you try stepping through each step [on this page](https://getdkan.github.io/dkan-tools/#newproject.html) to narrow down where exactly the build is falling over.

**Comment by dafeder** [comment]
As dkan-tools support will be ending soon and this issue is quite old, closing this. @kkounouni please open a new issue here or in the [DKAN discussion forum](https://github.com/GetDKAN/dkan/discussions) if you continue to have issues with this.
