### ISSUE TITLE
Update php.ini within containers

### ISSUE THREAD

**Issue by Katsivelisp** [GetDKAN/dkan-tools#324]
Hello,

I was wondering what's the way to update PHP variables (such as max_file_uploads) within the containers that are generated by DKAN tools. I noticed that these can be configured within the php.ini found in the dkan-cli container, but I would rather not access the container and change them manually. 

So, is there a way to modify php.ini and apply changes to the running containers without re-building/resetting my custom project?

Thanks for the good work!

**Comment by dafeder** [comment]
Hi @Katsivelisp! The `cli` container in DKAN tools, which is where PHP runs from, scans src/docker/etc/php in your project folder for ini files. So anything you put there should get picked up. 

See https://github.com/GetDKAN/dkan-cli/blob/master/Dockerfile#L8

You will probably need to restart your cli container after making any changes.

**Comment by Katsivelisp** [comment]
Hi @dafeder. This works great, thank you!
