### ISSUE TITLE
Do test migration of existing dkan-starter site to DKAN-tools

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan-tools#44]
## Acceptance criteria

- All modules currently managed through DKAN starter are added to DKTL make files or DKAN
- CircleCI and Probo work for PRs
- Confirm local development environment and CI can load production DB and files and deploy

**Comment by fmizzell** [comment]
Blocked: Waiting on #48 and #49 to land

**Comment by kimwdavidson** [comment]
@fmizzell adding QA instructions and then assigning to janette

**Comment by dafeder** [comment]
Findings:
1. Probo sites are missing files - sites are missing CSS/theming. File perms?
2. Tests are failing on project sites that should be passing when we switch to DKTL

Create two tickets:
1. Files not working correctly in probo
2. Why are DKAN tests failing in circle? Same as the probo problem?

**Comment by fmizzell** [comment]
Here are the tickets:
#54 
#56
