### ISSUE TITLE
Consolidate restore/install from backup commands

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan-tools#65]
The 'dkan:restore` command restores the db from a dump at a URL. The `dkan:install` command restores a db backup from the /backups folder if given a `-b` switch. These could be consolidated to make all this more intuitive.

## Acceptance Criteria

1. Take the `restore` command out of the `dkan` namespace.
2. Make the `restoreDb()` command public instead of private, so we can do either `dktl restore` for both or `dktl restore:db` for just the db.
3. Make the `restoreDb()` method restore from a URL if given the argument.
4. If the argument is not a URL, assume it's a filename and look for it in the /backups folder.
5. If there is no argument, look in the /backups folder. If there is a single file in there, use that. If there are multiple, present the list as an interactive option.

For instance:

```
$ dktl restore:db

The following backups are available to restore:

[1] last_backup.sql
[2] some_other_backup.sql.gz
```

6. .sql, .sql.gz and .sql.zip files should all be supported

**Comment by janette** [comment]
fixed by #253
