### ISSUE TITLE
Run docker-compose up automatically if not running

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan-tools#7]
## Acceptance criteria

* If a dktl command fails with the message `ERROR: No container found for cli_1` this should be detected by the bash script
* If this occurs, the script it should run `docker-compose up -d`
* After that command completes, it should try again. If the command fails with the same error message, it should quit

**Comment by dafeder** [comment]
@fmizzell I originally wrote this to check for docker _before_ executing a dktl command but realized that would slow down execution significantly (as would just running `docker-compose up -d` every time we run any command, which is what our first iteration does).

**Comment by fmizzell** [comment]
This is done
