### ISSUE TITLE
Allow override of docroot/.htaccess

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan-tools#73]
### Acceptance Criteria
- Adding a custom .htaccess file to the /src directory would override the docroot/.htaccess file

**Comment by dafeder** [comment]
I've done this successfully with existing tools. 

1. First, make the changes you want to .htaccess, and use whatever your favorite process is to create a patch file. What I do is make the change, do `git diff .htaccess > htaccess-patch.patch`, then revert the change (`git checkout .htaccess`).

My resulting file looks like this:

```diff
diff --git a/docroot/.htaccess b/docroot/.htaccess
index 37fce10..37b6fdb 100644
--- a/.htaccess
+++ b/.htaccess
@@ -152,3 +152,5 @@ DirectoryIndex index.php index.html index.htm
   # Disable content sniffing, since it's an attack vector.
   Header always set X-Content-Type-Options nosniff
 </IfModule>
+
+# TESTING .htaccess PATCH
\ No newline at end of file
```

2. Place your patch file in _/src/patches/_ (the actual path doesn't really matter as long as it's outside _/docroot_)

3. Add some lines like this to _/src/make/drupal.make_:
```yaml
projects:
  drupal:
    patch:
      1: ../src/patches/htaccess-patch.patch
```

4. Next time you run `drupal:make` (soon to be replaced by `make:drupal` or just `make`) the patch should apply. Note that the patch file will also be copied into the project directory (docroot in the case of Drupal, the module folder if you're applying a local patch to a module), which is just some drush make weirdness we can't avoid.

**Comment by fmizzell** [comment]
@dafeder Awesome, this looks great to me, hopefully @janette can confirm that it works.
