### ISSUE TITLE
Document how to use dktl deploy logic with Acquia

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan-tools#92]
Acquia offers "cloud hooks" (https://docs.acquia.com/acquia-cloud/develop/api/cloud-hooks/) as a way for Acquia hosting users to perform certain tasks when new code is deployed, dbs are moved from one environement to another, etc. DKTL deployment is also a means to perform those kinds of actions locally or in other environments managed by DKTL. There is a way to connect these two things, to eliminate repetition. Creating some documentation on how to do this would be useful.

**Comment by janette** [comment]
@dafeder @dasumner @fmizzell this seems useful
